### ISSUE TITLE
bogons from addr_groups.conf

### ISSUE THREAD

**Issue by abl1** [fukawi2/husk#14]
In addr_groups.conf, [bogons] section
1. In "192.0.0.0/24" probably netmask is incorrect - in http://tools.ietf.org/html/rfc6333 it is /29 not /24
2. in RFC 6598 is added "provider's net" - 100.64.0.0/10

**Comment by fukawi2** [comment]
Thanks for the bug report. I will fix up point 1 to a /29. The CGN range is already in though: https://github.com/fukawi2/husk/blob/develop/src/husk.pl#L151
