### ISSUE TITLE
conflicting filename for /usr/bin/fire

### ISSUE THREAD

**Issue by valr** [fukawi2/husk#16]
Hi,
Since last upgrade in archlinux, the filename /usr/bin/fire is part of mesa-demos package. It's then conflicting with /usr/bin/fire provided by husk.

As a workaround, I've added this line in the PKGBUILD in the package function:
mv $pkgdir/usr/bin/fire $pkgdir/usr/bin/husk-fire

Is there any option to rename the fire command into something different ?
Thanks

**Comment by fukawi2** [comment]
Well that's a bit of a pain. I figured it would happen sooner or later.

I'd prefer to keep the command short, especially without a hyphen.

What do you think about renaming it to "fwfire"?

**Comment by valr** [comment]
fwfire looks good.
It doesn't conflict with any other package file and google returns me nothing linux/unix related.

**Comment by fukawi2** [comment]
Implemented in 'develop' branch. Will merge to 'master' at a later date. Thanks for reporting :)
